### ISSUE TITLE
Inject connection to factory

### ISSUE THREAD

**Issue by aktraore** [nestjsx/nestjs-amqp#392]
Hello @bashleigh, I have trouble injecting a connection to a factory. I would be willing to submit a documentation PR for this as mentioned in #21 , but more importantly for me the createConnectionToken needs to be exported by default from the package. At the moment it's only accessible via `import { createConnectionToken } from 'nestjs-amqp/dist/utils/create.tokens';` and not via `nestjs/utils`. Can I submit a PR that does that also or are you against exposing this function in that way ?

**Comment by bashleigh** [comment]
I'm not sure I follow? `createConnectionToken` I guess should be exposed? If it is not then yea :) you're welcome to open a PR to expose it!
